---
- name: Update credential in AWX
  hosts: localhost
  connection: local
  tasks:
    - shell: summon ./update_awx_credential.sh

- name: Build & Deploy Artifact to Docker
  hosts: all
  roles:
    - role: '{{playbook_dir}}'

  tasks:
    - name: Find out playbooks path
      shell: pwd
      register: ppath
    - debug: var=ppath.stdout

    - name: Copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: '{{ppath.stdout}}/Dockerfile'

    - name: Download artifact
      get_url:
        url: "{{artifact_url}}"
        dest: "{{ppath.stdout}}/app.war"

    - name: Build image
      shell: "docker build -t localhost:5000/cicd/securedemo:latest . -f {{ppath.stdout}}/Dockerfile"

    - name: Start the container
      docker_container:
        name: cicd_SecureDemo
        image: localhost:5000/cicd/securedemo:latest
        ports:
          - "8099:8099"
